name: calculator
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  google_sign_in: ^6.0.0
  provider: ^6.0.3
  shared_preferences: ^2.0.13
  fluttertoast: ^8.0.8
  connectivity_plus: ^2.3.0
  battery_plus: ^1.0.6
  cupertino_icons: ^1.0.6
  math_expressions: ^2.5.0
  dio: ^5.0.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
